Repository jiphyeonjeon-42/frontend, pull requests merged in 2021-09, with the labels that each got.

#14 MERGE : ENV 기본 적용 css 추가
  public/index.html
  src/css/reset.css
Labels: environment

#18 MERGE : REFACTOR 1440px 이상 화면에서의 반응형 여백 수정
  src/App.css
  src/App.js
  src/component/BackGround.js
  src/component/BookInfo.js
  src/component/Books.js
  src/component/Header.js
  src/component/Information.js
  src/component/Main.js
  src/component/MainHome.js
  src/component/MainNew.js
  src/component/MainPopular.js
  src/component/Question.js
  src/component/Search.js
  src/css/BackGround.css
  src/css/BookInfo.css
  src/css/Books.css
  src/css/Header.css
  src/css/Infomation.css
  src/css/MainHome.css
  src/css/MainNew.css
  src/css/MainPopular.css
  src/css/Question.css
  src/css/Search.css
Labels: refactoring

#22 MERGE: FIX 검색에서 상세페이지로 이동하는 경로 수정
  .gitignore
  src/component/BookInfo.js
  src/component/Books.js
  src/component/CategoryFilter.js
  src/component/Header.js
  src/component/Main.js
  src/component/Pagination.js
  src/component/Search.js
  src/component/Sort.js
  src/css/BookInfo.css
  src/css/Books.css
  src/css/CategoryFilter.css
  src/css/Header.css
  src/css/Pagination.css
  src/css/Search.css
  src/css/Sort.css
  src/img/arrow_left_black.svg
  src/img/arrow_right_black.svg
  src/img/check_icon.svg
  src/img/link_to_detail.svg
Labels: usecase-1

#26 MERGE: FEATURE 카테고리 필터와 정렬 기준을 추가한 검색 api 사용
  package-lock.json
  src/component/BookDetail.js
  src/component/BookInfo.js
  src/component/Books.js
  src/component/CategoryFilter.js
  src/component/Main.js
  src/component/MainNew.js
  src/component/MainPopular.js
  src/component/Pagination.js
  src/component/Search.js
  src/component/Sort.js
  src/css/BookDetail.css
  src/css/CategoryFilter.css
  src/css/Footer.css
  src/css/Sort.css
  src/img/check_icon_red.svg
Labels: usecase-1

#29 MERGE FIX 인기도서 픽셀값 수정
  src/css/MainPopular.css
  src/css/MainPopularBook.css
Labels: usecase-4

#33 ENV: withCredential option 추가, api url 변경
  src/component/Books.js
  src/component/Header.js
  src/index.js
Labels: environment
