Repository jiphyeonjeon-42/frontend, pull requests merged in 2023-07, with the labels that each got.

#513 feat: 태그 상세 페이지 css 개선
  src/asset/css/Tags.css
  src/component/book/tag/TagList.tsx
Labels: 사용자, UI/UX

#521 fix: 메인페이지 인기 도서 순위 오류 해결
  src/api/books/useGetBooksInfoNew.ts
  src/api/books/useGetBooksInfoPopular.ts
  src/component/main/MainNewBook.tsx
  src/component/main/MainNewBookList.tsx
  src/component/main/MainPopularCenter.tsx
  src/component/main/MainPopularSide.tsx
Labels: 버그, 사용자

#524 docs: :memo: README에 이름추가하기
  README.md
Labels: 문서
